# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "aula_actions_1" ]
  pull_request:
    branches: [ "aula_actions_1" ]

jobs:

  teste:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.15', '1.18', '>1.19']  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
        
    - name: Build do Banco
      run: docker-compose build

    - name: Roda o Banco
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go

  pronto:
    needs: teste
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -v main.go
